### ISSUE TITLE
OSX Compatibility check-list

### ISSUE THREAD

**Issue by Adrion** [OFFLINE-GmbH/oc-bootstrapper#12]
Hi, 
I work on OSX and oc-bootstrapper works fine. 
But do you have a check-list I can test and say if it's fully compatible on OSX ?

**Comment by tobias-kuendig** [comment]
Thanks for your feedback. There is no such checklist. Since macOS and Linux usually run some kind of bash shell there should not be too many compatibility problems. If you can run an `october init` and  `october install` with both `bareRepo: true` and `bareRepo: false` everything should work!
