### ISSUE TITLE
Support for database behind SSL

### ISSUE THREAD

**Issue by colthreepv** [OFFLINE-GmbH/oc-bootstrapper#15]
I am certain this is a niche requirement, lately I am using a SSL protected mysql server remotely for dev/staging environments.

This kind of setup breaks hard oc-bootstrapper, because it does not support SSL config, and the database/migration part gets broken.

Any suggestions how to still use this handy tool?

To make it work (after the script has done it's job) I usually briefly edit `database.php` adding some custom SSL-related variables

**Comment by tobias-kuendig** [comment]
What variables are you adding? Can you provide me a working ssl
configuration?

Valerio Coltrè <notifications@github.com> schrieb am Mi., 26. Juli 2017,
04:39:

**Comment by colthreepv** [comment]
Sure, this is a glipse of my config files

**.env**
```ini
...
DB_CONNECTION=mysql
DB_HOST=remote.host.com
DB_PORT=3306
DB_USERNAME=username
DB_PASSWORD=password
DB_DATABASE=database
DB_USE_SSL=true
DB_SSL_KEY=certs/client-key.pem
DB_SSL_CERT=certs/client-cert.pem
DB_SSL_CA=certs/ca.pem
...
```

**config/database.php**
```php
        'mysql' => [
            'driver'    => 'mysql',
            'host' => env('DB_HOST', 'localhost'),
            'port' => env('DB_PORT', ''),
            'database' => env('DB_DATABASE', 'database'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', ''),
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
            'options'   => env('DB_USE_SSL') ? array(
                PDO::MYSQL_ATTR_SSL_KEY  => env('DB_SSL_KEY', ''),
                PDO::MYSQL_ATTR_SSL_CERT => env('DB_SSL_CERT', ''),
                PDO::MYSQL_ATTR_SSL_CA   => env('DB_SSL_CA', '')
            ) : array(),
        ],
```

**Comment by tobias-kuendig** [comment]
The problem here is that the `options` key for the mysql config currently is not shipped by default. The current setup of the config writer only works if the configuration key is already available an can be replaced with your desired values. 

To make this feature work we'd have to do extend this functionality which is a lot of work for a feature I'm sure not many users will use. Feel free to submit a PR but at the moment I do not have the resources to work on this.
