### ISSUE TITLE
OctoberCMS releases develop state 

### ISSUE THREAD

**Issue by Adrion** [OFFLINE-GmbH/oc-bootstrapper#16]
Hi,
If you check https://github.com/octobercms/october/releases/tag/v1.0.420 (latest)
the release is based on develop branch 😕 

The problem is that some people like https://bitbucket.org/flynsarmy/oc-sociallogin-plugin
Starts to use it as a requirement.

So now when I do `october install ` it fails since it downloads master.zip

What do you think ? I tried /releases/latest to change the download target in oc-bootstrapper but 
they don't have any hook on ...

**Comment by tobias-kuendig** [comment]
[We always download the master branch](https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/src/Downloader/OctoberCms.php#L57) and ignore the tags.

It looks to me like the `oc-sociallogin-plugin` updated `laravel/socialite` to version `3.0` which requires Laravel 5.4 components which are not available until October Build 420 is shipped.

As far as I can tell the problem has to be resolved by `oc-sociallogin-plugin`. They cannot require 5.4 components while publishing to the stable October channel. If they only publish this new version to the edge channel it will work but not with the current stable setup.

Your `composer install` won't work if a plugin requires 5.4 components while everything in October runs on 5.0.

The fact that [tag 1.0.420 is created on the develop branch](https://github.com/octobercms/october/issues/3066) shouldn't make a difference in this case.

**Comment by Adrion** [comment]
I agree, i think i will have to make a fork of the latest build of oc-sociallogin-plugin

But it stills weird that 420 is release but from develop.

**Comment by Adrion** [comment]
Rrrrr... as a private url plugin, it doesn't run the composer install... like with artisan.

this plugin update ruins my setup... I have to check this with the author...
