### ISSUE TITLE
Private plugin - composer deps

### ISSUE THREAD

**Issue by Adrion** [OFFLINE-GmbH/oc-bootstrapper#17]
We should check if there's any composer.json or composer.lock files after checkout.

here : https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/src/Installer/PluginInstaller.php#L68

**Comment by Adrion** [comment]
```$repo = Repository::open($pluginDir);
            try {
                $repo->cloneFrom($remote, $pluginDir);
                if ($branch !== false) {
                    $this->write('<comment>   -> ' . sprintf('Checkout "%s" ...', $branch) . '</comment>');
                    $repo->checkout($branch);
                }
                 (new Process("cd ".$pluginDir." && composer install"))->run();
            } catch (RuntimeException $e) {
                $this->write('<error> - ' . 'Error while cloning plugin repo: ' . $e->getMessage() . '</error>');
                continue;
            }```

This works but it uses `&&` and it may adds some compatibility issues with windows

**Comment by tobias-kuendig** [comment]
Composer is already configured to install all dependencies of all plugins when `composer install` is run. 
https://github.com/octobercms/october/blob/master/composer.json#L58

We only need to call `composer install` a second time after the plugins are installed or better postpone the composer call until the very end if possible.

**Comment by tobias-kuendig** [comment]
Checkout version 0.2.13 and see if this fixes your problem.

    composer global update

**Comment by tobias-kuendig** [comment]
Closing this issue since the feature has been implemented.
