### ISSUE TITLE
Install plugins from projects

### ISSUE THREAD

**Issue by Alex360hd** [OFFLINE-GmbH/oc-bootstrapper#18]
Hello,

October CMS provide a nice feature add some plugins to a project and sync a website with a project ID.

Would it be possible to add this feature to your bootstraper ? I imagine something like this : 

    project: project_api_key

Where project_api_key is the api key found on october cms website.

Thanks !

Alex

**Comment by tobias-kuendig** [comment]
What would be your use case for this? As far as i know `oc-bootstrapper` covers all the functionality the projects feature of October provides.

**Comment by Alex360hd** [comment]
For example, when you sync a website with a project ID, and that you add some new plugins into that project. When you will hit the "update" button of october CMS, it will install all new plugins detected.

With your system, I think that you have to manually update the config file and put the new plugin in the list in order to add it when you update isn't it ?

**Comment by tobias-kuendig** [comment]
Our workflow (as intended when using oc-bootstrapper) is:

1. Add new plugin to `october.yml`
2. Push to Git repo
3. Our CI system deploys the new code to the server and runs `october install` which picks up the new plugin from the configuration file and installs it.

Since we do not use any October projects I do not have a use case for this feature and will probably not implement it. If someone wants to submit a PR I'll merge it though.

**Comment by damsfx** [comment]
Hi,

The only case this feature may present an interest is with payed plugins.
They're necessarily attached to an project ID in October's marketplace.

How does your script react if the plugin list contains a paid plugin? (ex: Renatio.Formbuilder or Indikator.BackendElite )

**Comment by tobias-kuendig** [comment]
If you run the bootstrapper for the first time it will fail to install the plugin. If you then link your installation via the backend to a project any subsequent run of the bootstrapper should work since it simply calls `php artisan plugin:install X.Y` behind the scenes.

**Comment by obuchmann** [comment]
We could implement this very easy if this Feature gets pulled into october: 
https://github.com/octobercms/october/issues/3944

Would be one call to `artisan october:util set project --projectId=<id>` before starting the calls to `plugin:install`

Moreover: The current Implementation of `october:utils set project` does not download any plugins, like the set Project in the Backend does.

**Comment by obuchmann** [comment]
Looking forward to an PR.

Should we create a separate installer class in `src/Installer` and call it from InstallCommand or just invoke the artisan command if config parameter is set inside the InstallCommand?

What do you think?

**Comment by tobias-kuendig** [comment]
I haven't look into the details yet but it might be already enough to call the artisan command before the plugins are being installed:

https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/src/Installer/PluginInstaller.php#L46

The command can be executed similar to the install commands:

https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/src/Installer/PluginInstaller.php#L181

Maybe we could refactor the `installViaArtisan` method to be more generic and pull it up into the `BaseInstaller` class (the ThemeInstaller makes use of this as well)
