### ISSUE TITLE
Dev configuration should be more .env centric

### ISSUE THREAD

**Issue by cdarken** [OFFLINE-GmbH/oc-bootstrapper#2]
I believe that the configuration should be more easy for collaboration development.
What I mean is that the values taken from october.yaml should be saved in the .env file and in the config files we should have calls to the env() function, the Laravel standard way. I've commited my work from another computer and cloned into another and I was surprised that I cannot find the files in config/dev/, because there's a .gitignore inside it.
A command for the october script that creates  a new .env file from october.yml could be useful I think.
I might find a bit of time to try and write a pull request in the near future if you think it's a good idea.

**Comment by tobias-kuendig** [comment]
This is actually a problem I have experienced myself. When cloning the project on another machine the dev config is gone.

I like the idea of writing the values into the .env file and have a command regenerate it on demand. This way we could include all the dev config files in the repo and all that has to be edited or exluded is the .env file.

I'm all in for this feature. Thanks for your input!

**Comment by cdarken** [comment]
Glad to be of help, at least with ideas, for now :)

**Comment by tobias-kuendig** [comment]
Moved all configuration values to `.env` in [version 0.1.0](https://github.com/OFFLINE-GmbH/oc-bootstrapper/releases/tag/v0.1.0)

Thanks again for your input!

**Comment by cdarken** [comment]
Awesome, thanks!
