### ISSUE TITLE
Git bash - windows - templates location

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-bootstrapper#24]
It look's like on windows with git bash,  
the script don't look in `~/.config/composer/october/` but in `~/AppData/Roaming/Composer/october/` for overwriting templates.

**Comment by tobias-kuendig** [comment]
Yes, this is the correct and a known behaviour. Composer's configuration is stored in the AppData folder under windows.

I've updated the README to document this.

Thanks!
