### ISSUE TITLE
installation failed on MacOS

### ISSUE THREAD

**Issue by chrisvidal** [OFFLINE-GmbH/oc-bootstrapper#3]
here is the error after running the composer comand line

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for offline/oc-bootstrapper ^0.1.0 -> satisfiable by offline/oc-bootstrapper[v0.1.0].
    - Conclusion: remove guzzlehttp/guzzle 5.3.0
    - Conclusion: don't install guzzlehttp/guzzle 5.3.0
    - offline/oc-bootstrapper v0.1.0 requires guzzlehttp/guzzle ~6.0 -> satisfiable by guzzlehttp/guzzle[6.0.0, 6.0.1, 6.0.2, 6.1.0, 6.1.1, 6.2.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.1, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.0.2, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.1.0, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.1.1, 5.3.0].
    - Can only install one of: guzzlehttp/guzzle[6.2.0, 5.3.0].
    - Installation request for guzzlehttp/guzzle (locked at 5.3.0) -> satisfiable by guzzlehttp/guzzle[5.3.0].


Installation failed, reverting ./composer.json to its original content.```

**Comment by tobias-kuendig** [comment]
Thanks for reporting the issue.

It seems like you have a globally installed composer package that rerquires guzzle 5.3. That's what triggers the version conflict.

To work around this issue you could create a standalone installation of `oc-bootstrapper` like this:

```bash
cd /some/directory/oc-bootstrapper
composer require offline/oc-bootstrapper
```

You can now run `oc-bootstrapper` by calling it with it's absolute path:

```bash
/some/directory/oc-bootstrapper/vendor/bin/october --version
```

You can add this directory to your `PATH` afterwards.

**Comment by chrisvidal** [comment]
Thanks Tobias for the turnaround, it works great 👍 
however, after running the `october install` command  :
```Downloading latest October CMS...
Installing composer dependencies...
Setting up config files...
Migrating Database...
Migrations failed!
Removing demo data...
Failed to remove demo data!
Clearing cache...
Failed to clear compiled files!
Failed to clear cache!
Installing Theme...
Installing Plugins...
Error while installing plugin rainlab.pages via artisan. Is your database set up correctly?
Setting up deployments...
Creating .gitignore...
Creating README...
Cleaning up...
Application ready! Build something amazing.```

the default October database has not migrated, none of the plugins have been installed, only my theme has been upload from my git.

**Comment by chrisvidal** [comment]
after some digging, it looks like the command ```composer install``` didnt went through (my vendor folder is empty), then the command ```php artisan october:up``` can not be executed properly.

**Comment by tobias-kuendig** [comment]
Do you have composer installed globally? Can you exec `composer install` from anywhere?

**Comment by chrisvidal** [comment]
yes i can use composer from everywhere.
i had to use the command ```sudo october install``` to make it work.
but still the migration of october does not seem to work
```Downloading latest October CMS...
Installing composer dependencies...
Setting up config files...
Migrating Database...
Migrations failed!
Removing demo data...
Failed to remove demo data!
Clearing cache...
Installing Theme...
Installing Plugins...
Setting up deployments...
Creating .gitignore...
Creating README...
Cleaning up...
Application ready! Build something amazing.```

**Comment by chrisvidal** [comment]
i musing a MAMP stack, therefore it is using a unix_socket for the MySQL connection here.
i tried to add `unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock` in the `october.yaml` but no effect

**Comment by tobias-kuendig** [comment]
> i had to use the command sudo october install to make it work.

Well, this seems like a permissions problem then. Not much I can do about that. 

> i musing a MAMP stack, therefore it is using a unix_socket for the MySQL connection here.

You should be able to connect to the database without the use of the socket. IIRC the default port on MAMP is 8889. 

Could you try using `localhost:8889` as database host and see if that works?

**Comment by chrisvidal** [comment]
i tried with `localhost:8889` and `localhost:3306` but migration failed as well.

is it normal that the `dev` folder is empty ? i got no config file inside, which will explain the database problem, right ? if that so, then the question is why this folder is empty

**Comment by tobias-kuendig** [comment]
No, that's correct. All variables are taken from your `.env` file. You can overwrite them in the `dev` folder if necessary but you don't have to.

Does it work if you edit your `config/database.php` manually? Add `host => localhost` and `port => 8889` and see if it works.

Alternatively you should be able to set the unix socket like this:

```php
    'mysql' => [
            'driver'    => 'mysql',
            'host'      => env('DB_HOST'),
            'port'      => '',
            'database'  => env('DB_DATABASE'),
            'username'  => env('DB_USERNAME'),
            'password'  => env('DB_PASSWORD'),
            'unix_socket'   => '/Applications/MAMP/tmp/mysql/mysql.sock',
            'charset'   => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix'    => '',
        ],
```
Does this work?

**Comment by chrisvidal** [comment]
actually i just realize while trying to edit the config/database.php that i dont have any permission right on all the files and folder build from oc-bootstrapper

**Comment by tobias-kuendig** [comment]
It looks like the permissions in your directory are all wrong. 

Try to run `sudo chown your-username:your-username /path/to/your/directory` and see if this fixes the problems.

**Comment by chrisvidal** [comment]
after `sudo october install` then the command `sudo chown -R your-username /path/to/your/directory` then edit the config/database.php file to insert the unix_socket, then run the command `php artisan october:up` 

got it to work  like that ! now i need to figure out the whole permission thing with composer that is the root of the issue here

thanks for your help Tobias
