### ISSUE TITLE
Error in Envoy.blade.php

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-bootstrapper#35]
Hi all,   

I've got a new error using October CMS Bootstrapper v0.5.2.

````
bash: line 22: composer.phar: command not found
````
The line is :
````
$PHP composer.phar self-update
````
Changed to 
````
php composer.phar self-update
````
and all is all right !

**Comment by tobias-kuendig** [comment]
Thank you! This will be fixed in 0.5.3.
