### ISSUE TITLE
Install not working: Octobercms Git Master Branch deleted

### ISSUE THREAD

**Issue by obuchmann-pc-web** [OFFLINE-GmbH/oc-bootstrapper#45]
https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/5a3ea802f7c5d72e61c452396df061fdd25f7f6e/src/Downloader/OctoberCms.php#L87

There is no more master branch in Octobercms Github.

**Comment by Ma3ffin** [comment]
I can confirm that

**Comment by tobias-kuendig** [comment]
Looks like they've changed the branching model. I'll wait for any official news before fixing this issue.

In the meantime, you can manually patch the `master` part of the URL to `1.0` which should work.

**Comment by tobias-kuendig** [comment]
This is fixed in version 0.9.0. Thank you both for the report!
