### ISSUE TITLE
Usage instruction for docker image

### ISSUE THREAD

**Issue by alxy** [OFFLINE-GmbH/oc-bootstrapper#52]
Hi,

I tried to use the provided Docker image to run the `october init` and `october install` commands. I like the idea of having everything in Docker, however, the documentation on this topic is a bit lacking.

The first thing I realized is that to make practical use of the image you need to mount a volume to sync files between the container and the host machine. However, that is easier said than done, as the working directory of the container (`/composer`) is non-empty and thus [cannot easily be mounted](https://docs.docker.com/storage/bind-mounts/#mount-into-a-non-empty-directory-on-the-container).

That beeing said, what I needed to do was modify the `Dockerfile` (and build a custom image) to include a separate working directory for the "application" files, namely the `october.yaml` in this case to successfully run the init command:

```
RUN mkdir /home/app
WORKDIR /home/app
```

```bash
$ docker run -v $(pwd):/home/app bootstrapper october init mytest
Please select a dev environment to set up
  [0] Do not set up an environment
  [1] lando.dev development environment
 > Creating project directory...
Updating template files...
Creating default october.yaml...
Done! Now edit your october.yaml and run october install.
```

**Comment by tobias-kuendig** [comment]
I have updated the README in f0854677c13532f727e764b28edbd4f9f9a1b758. If you have any further questions feel free to reply to this issue.
