### ISSUE TITLE
Question: need some help with Docker

### ISSUE THREAD

**Issue by snakemastr** [OFFLINE-GmbH/oc-bootstrapper#53]
Hi, 

I thought this project would be a great start at using Docker. I have followed the guides on using bind mounts, multiple container applications etc and I understand the process. But I don't understand what's going on with this image. I just cannot find the created october.yaml file in the bound volume.. 

Running the commands below in Git Bash on Windows
```
$ winpty docker run -it --rm -v /c/projects/docker/oct1:/app offlinegmbh/oc-bootstrapper october init
# results in empty dir oct1;C

$ winpty docker run -it --rm -v //c/projects/docker/oct1://app offlinegmbh/oc-bootstrapper october init test
# nothing

$ winpty docker run -it --rm -v "$(pwd)":/app offlinegmbh/oc-bootstrapper october init test.dev
# results in empty dir october;C
```

In all cases I get the same prompt and output:
```
Please select a dev environment to set up
  [0] Do not set up an environment
  [1] lando.dev development environment
 > 0
Creating project directory...
Updating template files...
Creating default october.yaml...
Done! Now edit your october.yaml and run october install.
```

Some help would be much appreciated!

**Comment by tobias-kuendig** [comment]
You can get an interactive shell by running the `bash` command:

```
docker run -it --rm -v "$(pwd)":/app offlinegmbh/oc-bootstrapper bash
```

You can then run `ls /app` to see if your volume is correctly mounted inside the container (you should see your files). You can also simply run `october init` to initialize a project. Type `exit` to leave the container.

**Comment by snakemastr** [comment]
Hi Thomas,

thank you for replying. In the meantime I switched to PowerShell and got it working when I set the working directory to /app so full command is now 

```
docker run -it --rm -w /app -v "$(pwd):/app" offlinegmbh/oc-bootstrapper october init test.com
```
I think I should have taken some more time to play around in the image itself because that was how i figured I was not running in the mounted directory /app in the image like you said. 

Really cool work what you've done, also with the Mall plugin. Love it!

**Comment by snakemastr** [comment]
I have yet one question.

Would you run the server by using artisan serve or run a separate nginx container with the same mounted volume?

**Comment by tobias-kuendig** [comment]
The bootstrapper container is not meant to run October, it simply installs all required dependencies. It actually only works for the `init` command without further setup. If you want to run an `install`, you have to make sure the container has a DB to connect to (or configure SQLite). In most cases, this means you have to integrate it with Docker Compose.

If you are looking for a nice dev setup for October using Docker, I suggest you look into [lando.dev](https://lando.dev/).

It works great with WSL2 and Docker on Windows after the initial configuration. We do have documented our setup on our blog: https://offline.ch/blog/wsl (it is written in German but you should be able to get the relevant parts from the screenshots/code snippets or use a translator).

With Lando + the oc-bootstrapper you only need two commands "from zero to October". No local dependencies are required (except Docker):

```bash
# This could be aliased to "october" for easier access
docker run -it --rm -v "$(pwd)":/app offlinegmbh/oc-bootstrapper october init 
# 1. Select the lando.dev option
# 2. Edit the october.yaml file, then

lando start
```

**Comment by snakemastr** [comment]
Thank you Thomas, 
I had the MySQL image connected using the networking method as explained on the Docker guide for Multiple containers..
I'm checking out Lando as I'm typing but it fails to install composer so I'll have to dive into that. But it looks very promising with the mailhog and proxy also.

Thank you so much :)

**Comment by snakemastr** [comment]
I have setup the system like described in your blog and am running lando in WSL. 
Unfortunately I get "Failed to run composer install:" and then some errors about Missing vendor files (due to composer not installing). The composer won't install dependencies on lando start or lando rebuild. adding verbose flags like -vvv do give me information but not about why composer failed. 
Could this be a configuration issue? I have followed the steps in the blog to the letter and did not make any changes to the standard october.yaml

**Comment by snakemastr** [comment]
It appears that I installed all latest versions and Lando switched to composer 2. I had to update .lando config to use composer_version:1 and also removed all containers. I then set up all from scratch and it worked! Perhaps I had some stale connections or something. Thank you
