### ISSUE TITLE
Hostname %deployment.server%: Name does not resolve

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-bootstrapper#55]
Well ... It's all in the title! 

Getting this error when trying to use variables replacments in my Envoy.blade.php file.

**Envoy.blade.php** :
```` 
@setup
    // Deployment configuration ----------
    $project      = '%app.hostname%';
    $user         = '%deployment.user%';
    $server       = '%deployment.server%';
    $directory    = '/home/%app.hostname%/public_html';
    $slackWebhook = '';
    // -----------------------------------

    $author = isset($author) ? $author : "someone";
    $branch = isset($branch) ? $branch : "unknown branch";
    $commit = isset($commit) ? $commit : "no message";
@endsetup
````
**october.yaml** :
````
# deployment: false
deployment:
    user: my_cdci_user
    server: server_url
````
and finaly my error :
````
$ envoy run deploy \ # collapsed multi-line command
[%deployment.user%@%deployment.server%]:  ssh: Could not resolve hostname %deployment.server%: Name does not resolve
````

A question to remove a doubt ... the correct syntax for a server with a port is `server: server_url -p 00000` or `server: 'server_url -p 00000'`  ??

**Comment by tobias-kuendig** [comment]
The `%variables%` should be replaced when you run `october init/install`. You can only use the variables [in template files](https://github.com/OFFLINE-GmbH/oc-bootstrapper#file-templates), do you use them? 

> A question to remove a doubt ... the correct syntax for a server with a port is server: server_url -p 00000 or server: 'server_url -p 00000' ??

Do you want to connect via SSH on another port than 22? In this case you can change the `@servers` directive to also use a port:

https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/templates/Envoy.blade.php#L15

```blade
@servers(['web' => $user . '@' . $server . '-p 2222', 'localhost' => '127.0.0.1'])
```


... or add it in the $server variable, but i'm not sure if Envoy escapes these values. You'll have to try.
