### ISSUE TITLE
Error with hidden plugins from marketplace

### ISSUE THREAD

**Issue by damsfx** [OFFLINE-GmbH/oc-bootstrapper#56]
Hidden plugins (from the market place) present in `october.yaml` file, result in an error.  
````
Error while installing plugin Luketowers.Twigpcre via artisan:

  Error running "php artisan plugin:install Luketowers.Twigpcre" command:
  In UpdateManager.php line 867:

    The plugin is hidden and cannot be installed
````

Setting the plugin's repo in october.yaml solve issue.

````
    # - Luketowers.Twigpcre
    - ^Luketowers.Twigpcre (git@github.com:LukeTowers/oc-twigpcre-plugin.git)
````

Have to do the same for all @LukeTowers plugins. 😢

**Comment by LukeTowers** [comment]
@damsfx they did that to me, I didn't do that. All my October plugins will be available soon as Winter plugins :)

**Comment by tobias-kuendig** [comment]
Thanks @damsfx but this is expected behaviour. If you install a plugin that is hidden or does not exist it should give you an error. We are just calling `php artisan plugin:install` under the hood, so we are depending completely on October's native installation methods.
