### ISSUE TITLE
OctoberCMS 2.0 Support?

### ISSUE THREAD

**Issue by artistro08** [OFFLINE-GmbH/oc-bootstrapper#59]
Does this work with the current version of octobercms 2.0?

**Comment by tobias-kuendig** [comment]
You can check out the v2 branch:
https://github.com/OFFLINE-GmbH/oc-bootstrapper/tree/october-v2

It is not 100% stable so far, but will be soon. 

There are some changes required to your october.yaml:

- Add a `version: 2` key, to tell bootstrapper to install version 2 of October
- Optionally, add your license key as the `key` variable

See https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/october-v2/templates/october.yaml#L1-L5
