### ISSUE TITLE
Add Custom Plugin - Specific Branch or Tag

### ISSUE THREAD

**Issue by Adrion** [OFFLINE-GmbH/oc-bootstrapper#6]
Do we have a way to specify a branch for a custom plugin ?

I don't want to keep versioning in plugin repo AND in the website that requires it. (BareRepo)

But the problem is that we can't clone a specific branch of a plugin on specific env.
We should be able to add a branch or a tag target in plugin.git url.

I tried urls like `github.com/<user>/<project>.git#<branch>`  
or git clone options : `<url> --branch <branch> --single-branch` 
neither worked. 

I'll check how It can be done and make a PR :)

**Comment by Adrion** [comment]
after installation .git plugin's directory is removed. So we can't switch to a branch in CI.
I thinks that we shouldn't keep it. Maybe an option to switch just before cleaning the repo ?

**Comment by Adrion** [comment]
We can check if remote ends with .zip/.tar.gz to handle tag urls.

**Comment by tobias-kuendig** [comment]
I like the idea to provide an optional `#branch` to the git url.

You should be able to parse this branch suffix out here: https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/src/Installer/PluginInstaller.php#L93

Then you can use `$repo->checkout($branch);` to switch to the specified branch around here: https://github.com/OFFLINE-GmbH/oc-bootstrapper/blob/develop/src/Installer/PluginInstaller.php#L64 

You can checkout [GitElephant's docs](https://github.com/matteosister/GitElephant) for more information.

**Comment by Adrion** [comment]
Done in #7

**Comment by tobias-kuendig** [comment]
Great! Thank you!

Released as [0.2.9](https://github.com/OFFLINE-GmbH/oc-bootstrapper/releases/tag/v0.2.9)
