### ISSUE TITLE
Using oc-bootstrapper on existing dev-project

### ISSUE THREAD

**Issue by CitrinoDeveloping** [OFFLINE-GmbH/oc-bootstrapper#8]
Hi,

this plugin is a very good alternative to deploy and install private plugin.
So i'd like to do some question:

I have a dev machine tiith two projects is possibile to use oc-bootstrapper on existing project or it only works with project from scratch?

The part i love more is the private plugin install. So i have some dev-plugin on my gitlab and i want to create dependencies for my theme. Or i can create a octboer.yaml file only to update my exiting dev-website?

What do you think?

Bye!

**Comment by tobias-kuendig** [comment]
You should be able to use the bootstrapper with an existing project. Just make sure you place all plugins in your `october.yaml` that are currently installed and don't forget to create a backup before running `october install` for the first time. If you run into problems you can alternatively create a new installation using the bootstrapper and copy over your previous data (you'll only need to copy the plugins and themes folder).
